### ISSUE TITLE
Importing monitoring with AI

### ISSUE THREAD

**Issue by fxprunayre** [titellus/daobs#24]
```
<response>
<lst name="responseHeader"><int name="status">500</int><int name="QTime">24</int></lst><lst name="error"><str name="msg">Unable to initialize Templates 'inspire-monitoring-reporting-with-ai.xsl'</str><str name="trace">java.io.IOException: Unable to initialize Templates 'inspire-monitoring-reporting-with-ai.xsl'
	at org.apache.solr.util.xslt.TransformerProvider.getTemplates(TransformerProvider.java:115)
	at org.apache.solr.util.xslt.TransformerProvider.getTransformer(TransformerProvider.java:77)
	at org.apache.solr.handler.loader.XMLLoader.getTransformer(XMLLoader.java:197)

```

**Comment by fxprunayre** [comment]
Fixed in https://github.com/titellus/daobs/commit/dd7798c0677da1ff634724c78eba99c598d5bf4d
